[workspace]
resolver = "2"
members = [
  "fx-core",
  "fx-utils", 
  "fx-cli", 
]

default-members = [
  "fx-cli"
]

[workspace.package]
name = "fs"
version = "0.1.0"
edition = "2021"
authors = ["Radha", "Krsna"]

