[package]
name = "fx_cli"
version.workspace = true
edition.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fx_core = { path = "../fx_core" }
fx_utils = { path = "../fx_utils" }
